# This is a generated file. Not intended for manual editing.
services:
  basketserviceapi:
    build:
      context: "/home/george/git/BasketService"
      dockerfile: "src/BasketService.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/BasketService.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketserviceapi:dev"
    ports: []
    volumes:
    - "/home/george/git/BasketService/src/BasketService.Api:/app:rw"
    - "/home/george/git/BasketService:/src:rw"
    - "/home/george/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
